# Generated by Django 4.2 on 2023-04-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('title_prompt', models.CharField(max_length=1024)),
                ('title_gen', models.CharField(max_length=8192)),
                ('description', models.TextField()),
                ('description_prompt', models.TextField()),
                ('description_gen', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('generated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('title_prompt', models.CharField(max_length=1024)),
                ('title_gen', models.CharField(max_length=8192)),
                ('content', models.TextField()),
                ('content_prompt', models.TextField()),
                ('content_gen', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('generated_at', models.DateTimeField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chapters', to='books.book')),
            ],
        ),
    ]
