# Generated by Django 4.2 on 2023-06-08 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_book_updated_by_chapter_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description_prompt',
        ),
        migrations.RemoveField(
            model_name='book',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_gen',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title_prompt',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='book',
            name='conversation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='gpt_name',
            field=models.CharField(default='gpt-3.5-turbo', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='initial_prompt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='meta_prompt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
