# Generated by Django 4.2 on 2023-06-08 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description_gen',
            new_name='description',
        ),
    ]
