# Generated by Django 4.2 on 2023-06-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_description_gen_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='conversation',
            new_name='outline_prompt',
        ),
    ]
