# Generated by Django 4.2 on 2023-06-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_conversation_book_outline_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='outline',
            field=models.TextField(blank=True),
        ),
    ]
