# Generated by Django 4.2 on 2023-06-09 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_alter_book_created_at_alter_book_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='content_gen',
            new_name='chapter_prompt',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='title_prompt',
            new_name='gpt_name',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='content_prompt',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='title_gen',
        ),
        migrations.AddField(
            model_name='chapter',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='revise_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='revised_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_chapters', to=settings.AUTH_USER_MODEL),
        ),
    ]
